Tenant Ownership documentation
clastix/capsule pull request #414
Opened 2021-09-05 12:40 UTC by oliverbaehler

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>

I have added some documentation about Tenant Ownership regarding OIDC and ServiceAccounts (Since I haven't found it anywhere else in the documentation). I don't know if it's helpful, but it would have spared me some hours if I knew these things.. :) 

Maybe we could also move the part from the Main README (https://github.com/clastix/capsule/blob/master/README.md#tenant-owners) to this section and the just reference it. So that everything is in one place.

Have you thought about releasing the documentation via GitHub pages? Might be neat too and I could contribute a draft for that.

2021-09-05 14:11 UTC, prometherion commented
Thanks for your contribution, @oliverbaehler!

Documentation is absolutely a priority and we have to get a feedback by our expert, @bsctl.

2021-09-05 17:02 UTC, bsctl requested changes
Thanks @oliverbaehler for your contributions, really appreciate.

Tenant ownership, including ServiceAccount, is documented [here](https://github.com/clastix/capsule/blob/master/docs/operator/use-cases/onboarding.md#assign-a-robot-account-as-tenant-owner). Please merge your comments there and do not add another section.

About OIDC, I do not think it should be added in Capsule documentation since:

- Capsule is agnostic about the authentication method used in Kubernetes
- Authentication via OIDC is well documented in Kubernetes documentation
- OIDC has many ways to be configured and the way you mentioned in your comment is just one.

2021-09-05 17:11 UTC, bsctl commented
> Have you thought about releasing the documentation via GitHub pages? Might be neat too and I could contribute a draft for that.

@oliverbaehler Plan is to publish documentation with Hugo and Netlify. Have #397 open, PRs are really welcome.

2021-09-06 16:03 UTC, oliverbaehler commented
@bsctl Thanks for the review. Sorry for missing that in the documentation.

2021-09-06 16:03 UTC, closed without merging