add documentation about deny-wildcard annotation
clastix/capsule pull request #433
Opened 2021-09-23 13:56 UTC by alegrey91

fixes #219.

2021-09-23 16:01 UTC, prometherion requested changes
LGTM, just needs to be rebased over the latest `master`.

2021-09-23 16:34 UTC, prometherion approved these changes

2021-09-23 16:34 UTC, merged

2024-09-08 16:50 UTC, aminmr commented
I have a specific domain for my customers, such as freeexample.com, which is available for general use. However, for certain special users, I need to restrict access to creating an ingress with this domain. Do you have any ideas on how to achieve this?
@prometherion

2024-09-10 17:11 UTC, prometherion commented
@aminmr I would suggest you use the [Slack workspace channel](https://kubernetes.slack.com/archives/C03GETTJQRL) to ask for more information about the Capsule features.