Resolve Silent Rolebinding Drops
clastix/capsule pull request #457
Opened 2021-10-23 11:25 UTC by oliverbaehler

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>

Fixes #453 

**Changelog**
Fixed - Correctly configured rolebindings (includcing owner bindings) will be created even if there's wrong configured rolebindings.

I am not sure why that line was in there. In case of an error you just log the error but you shouldn't return. @prometherion maybe you have any idea why that's there?

Also added some additional commands/context to the dev guide. IDK why it changed the deepcopy, maybe version difference?

**Testing with the values from the issue you get the following behavior**:

All rolebindings that are valid are created:

```
kubectl get rolebinding -n gas-production --as system:serviceaccount:capsule-system:default --as-group capsule.clastix.io
NAME                        ROLE                                    AGE
capsule-bug-1-tenant-pass   ClusterRole/tenant-pass                 10s
namespace:admin             ClusterRole/admin                       10s
namespace-deleter           ClusterRole/capsule-namespace-deleter   10s
```
Faulty Rolebinding is logged:

```
2021-10-23T11:07:31.471Z	ERROR	controllers.Tenant	Cannot sync Additional RoleBinding	{"Request.Name": "bug", "error": "RoleBinding.rbac.authorization.k8s.io \"capsule-bug-0-tenant-faulty\" is invalid: [subjects[2].name: Invalid value: \"system:serviceaccount:default:default\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), subjects[3].name: Invalid value: \"system:serviceaccount:capsule-system:default\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]"}
github.com/clastix/capsule/controllers/tenant.(*Manager).syncAdditionalRoleBindings.func2
	/workspace/controllers/tenant/rolebindings.go:46
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
```

2021-11-01 10:03 UTC, oliverbaehler commented
@prometherion yes you were right:

```
golangci-lint run
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
pkg/webhook/tenant/rolebindings_regex.go:37:24: string `ServiceAccount` has 2 occurrences, make it a constant (goconst)
				if subject.Kind == "ServiceAccount" {
				                   ^
```

Added const declaration:

```
const (
	ServiceAccountSubject string = "ServiceAccount"
)
```

Lint now ran without failure:

``` 
golangci-lint run
WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
```

2021-11-02 16:16 UTC, prometherion requested changes

2021-11-02 16:16 UTC, prometherion commented on pkg/webhook/tenant/rolebindings_regex.go
> +	ServiceAccountSubject string = "ServiceAccount"
Let's use the Kubernetes constants: you could import `k8s.io/api/rbac/v1` in order to use the `ServiceAccountKind`.

https://github.com/kubernetes/api/blob/cca52a076791d31b1796453ece4b2f4df97406a2/rbac/v1/types.go#L35

2021-11-06 15:31 UTC, prometherion approved these changes
~LGTM, thanks for catching this, @oliverbaehler!~

Ah, damn... a conflict since we just merged a documentation refactoring! 😮‍💨 

I guess this will be the last requested change!

2021-11-12 10:22 UTC, merged