chore(description): description for limitRanges and update doc
clastix/capsule pull request #529
Opened 2022-03-15 23:14 UTC by gkarthiks

Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>

Provides the right description for the `limitRanges` in TenantSpec, in turn applying that to the generated CRDs and updating the reference document.

2022-03-16 08:26 UTC, prometherion requested changes
Thanks for this, we missed it!

Could you also provided the single YAML manifest installer? IIRC it can be generated using `make installer`

2022-03-16 10:24 UTC, prometherion requested changes
Let's squash the two commits in a single one using the `chore` message, rather.

Once done, heading to get it merged!

2022-03-17 16:52 UTC, gkarthiks commented
> Let's squash the two commits in a single one using the `chore` message, rather.
> 
> Once done, heading to get it merged!

Apologies for too many commits. Done what you have asked. Thank you!

2022-03-18 16:44 UTC, prometherion approved these changes

2022-03-18 16:44 UTC, merged