fix Makefile for building local binary with make manager
clastix/capsule pull request #542
Opened 2022-04-11 10:26 UTC by gernest

I tried to run `make manager` to make sure I can build capsure locally.

-> First attempt

```
make: *** No rule to make target `fmt', needed by `manager'.  Stop.
```

fmt and vet rules were missing. I added fmt and vet rules(as part of this commit)

-> Second attempt

```
go fmt ./...
go vet ./...
go build -o bin/manager main.go
./main.go:65:55: undefined: GitTag
./main.go:65:63: undefined: GitCommit
./main.go:65:74: undefined: GitDirty
./main.go:66:46: undefined: GitRepo
./main.go:67:46: undefined: BuildTime
make: *** [manager] Error 2
```

This is due to  passing main.go to build, while the package has multiple files
`main.go` and `version.go`, the missing symbols are in `version.go`

I fixed this by building root package. And now go is happy!

-> Third attempt

```
go fmt ./...
go vet ./...
go build -o bin/manager
```

2022-04-11 11:55 UTC, prometherion requested changes
Thanks @gernest for the hotfix, really appreciated it! 

Could you address the required changes? Once done, LGTM!

2022-04-11 11:55 UTC, prometherion commented on Makefile
>  manager: generate fmt vet
We already have linting enabled, you can use the target `golint` that is containing all the required rules.

2022-04-11 11:55 UTC, prometherion commented on Makefile
> +
No need to import back `fmt` and `vet`, let's rely only on target `golint`.

2022-04-11 12:14 UTC, gernest commented
@prometherion I made the changes PTAL.

2022-04-11 15:50 UTC, gernest commented
Done!

Thanks.

2022-04-12 10:12 UTC, prometherion approved these changes

2022-04-12 10:12 UTC, merged