[docs] clarify serviceAccounts as tenant owner
clastix/capsule pull request #645
Opened 2022-09-26 13:00 UTC by lalyos

after some discussion on slack with @prometherion here is my attempt to make the docs more clear.

> we don't know how's the platform admin is managing these ServiceAccount
We saw from other end-users that their best practice is to create a Namespace containing all the ServiceAccount resources that will be used as Tenant Owner (e.g: tenant-system) in order to user its group in the Capsule Configuration (e.g.: system:serviceaccounts:tenant-system).

2022-09-26 15:28 UTC, prometherion requested changes
LGTM, just a note regarding the commit message that is violating the semantic commit messages.

I would suggest something has `fix(docs): clarifying serviceaccount as tenant owner`

2022-09-26 16:38 UTC, lalyos commented
fixed the commit message

2022-09-26 17:11 UTC, bsctl approved these changes
@lalyos thanks for your work, it lgtm.

2022-09-27 12:15 UTC, prometherion approved these changes

2022-09-27 12:15 UTC, merged