HELM: Add control for securityContext for capsule pods
clastix/capsule pull request #693
Opened 2023-02-02 10:02 UTC by zvlb

Signed-off-by: Zemtsov Vladimir <vl.zemtsov@gmail.com>

Small feature for control securityContext in helm

2023-02-02 13:25 UTC, prometherion commented
Hey @zvlb, thanks for the PR! I think this is strictly related to #680 by @oliverbaehler: would be great if we could add the defaults detected by Oliver, and let run the `ct` job in this PR that we have that ensures `capsule` can start and bind to the network.

2023-02-02 13:27 UTC, prometherion requested changes
Please, adhere to the semantic commit messages, more info is available [here](https://www.conventionalcommits.org/en/v1.0.0/).

For Helm changes, I use `chore(helm)` as the subject, and remember to bump up the patch version in the `Chart.yaml` file so we can release a new Chart version.

Also, the Chart documentation must be aligned to the new changes, please, issue `make helm-docs` and commit the result.

2023-02-02 13:27 UTC, prometherion commented on charts/capsule/templates/daemonset.yaml
> +      {{-- end }}
It should be `{{- end }}`

2023-02-02 13:44 UTC, zvlb commented
Oliver has errors with securityContext, like:
`
securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1002
          runAsNonRoot: true
          runAsUser: 1002
`

Maybe now we will deploy a new chart version with control securityContext
Today or tomorrow I will test best practice for securityContext, and set PR with default values

2023-02-03 18:06 UTC, prometherion commented
May I ask you to add the required `securityContext` suggested by Oliver, along with your proposed fix?

2023-02-09 15:18 UTC, zvlb commented
I reopen this PR soon

2023-02-09 15:18 UTC, closed without merging