feat: custom container port
clastix/capsule pull request #717
Opened 2023-02-28 17:34 UTC by aslafy-z

2023-02-28 20:57 UTC, prometherion requested changes
Outstanding contribution, @aslafy-z!

May I ask you to split the changes into two commits? The first one with the code-base changes, the second with Helm ones, and a minor bump app of the Chart version.

The reason behind this is to decouple the Helm Chart from the code-base, so we can release both independently.

2023-02-28 21:00 UTC, prometherion commented
Please, along with the Helm changes, issue `make helm-docs` to generate the documentation.

2023-03-01 08:52 UTC, aslafy-z commented
Sure, I will make the changes! Do you want me to expose the webhookHost as well ?

2023-03-01 08:59 UTC, aslafy-z commented
@prometherion The appVersion minor will be bumped automatically, or do I need to do it?

2023-03-02 08:47 UTC, prometherion requested changes
Regarding the `appVersion` I was expecting to release it for v0.2.3, however, we accumulated some changes that must be addressed with v0.3.0.

Let's go for this, I'll publish the newer Chart once v0.3.0 is ready.

2023-03-02 08:47 UTC, prometherion commented on charts/capsule/Chart.yaml
> +version: 0.4.0
My personal experience: adding values doesn't require a minor bump, a patch is good enough.

We're using minor changes when updating the CRD definition, and major when changing or deprecating Helm values.

Please, let's coordinate with #718 to get it merged, and then bump up to the next patch version.

2023-03-03 18:03 UTC, prometherion commented
@aslafy-z I just contributed to your branch by fixing the conflict, going to merge this to proceed to tag Capsule v0.3.0 with several fixes and this enhancement.

2023-03-04 10:58 UTC, prometherion commented
Helm testing is failing due to v0.2.2 not being released on the main branch, going to merge this and fix this once v0.3.0 is cut off.

2023-03-04 10:58 UTC, prometherion approved these changes

2023-03-04 10:58 UTC, merged